#!/usr/bin/env python3
"""Mutation check for the contract tests.

Each mutation breaks one guarantee in `src/`. The run applies it, runs `forge test`, and
requires that every named test goes red (other red tests are listed too). It then
restores the file byte for byte.

    python3 scripts/mutations.py            # all (M contracts, P shared pool, G gateway, A agent client, K keeper, J app)
    python3 scripts/mutations.py M5 G2      # some

Exit 0 only if every mutation applied exactly once and turned every named test red. A
mutation whose text is not found is a failure of this harness, not a pass: otherwise a
refactor would quietly turn it into "survived" or "killed" without anything being tested.
Each suite first runs unmutated, and a named test that is already red there fails the run:
a test that was red before the mutation proves nothing about it.
"""

from __future__ import annotations

import os
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]

MUTATIONS = [
    ("M1", "src/RuledAccount.sol",
     "if (eq * bps < base * (bps - int256(uint256(_rules.maxDrawdownBps)))) return Breach.Drawdown;",
     "if (eq * bps <= base * (bps - int256(uint256(_rules.maxDrawdownBps)))) return Breach.Drawdown;",
     ["test_drawdown_boundary"]),
    ("M2", "src/RuledAccount.sol",
     "if (dayStartEquity > 0) {",
     "if (false) {",
     ["test_dailyLoss_boundary", "test_dailyLoss_countsFromTheDaysSnapshot"]),
    ("M3", "src/RuledAccount.sol",
     "if (uint256(m.ntlPos) * 100 > uint256(eq) * _rules.maxLeverageX100) return Breach.Leverage;",
     "if (uint256(m.ntlPos) * 100 >= uint256(eq) * _rules.maxLeverageX100) return Breach.Leverage;",
     ["test_leverage_boundary"]),
    ("M4", "src/RuledAccount.sol",
     "if (!_allowedAsset[a] && CoreOps.positionSize(address(this), a) != 0) return Breach.ForbiddenAsset;",
     "if (CoreOps.positionSize(address(this), a) != 0) return Breach.ForbiddenAsset;",
     ["test_forbiddenAsset_onlyWhenNamed"]),
    ("M5", "src/RuledAccount.sol",
     "            factory.registry().retire(old);",
     "",
     ["test_breach_cutsAgent_cancels_closes_thenSettles", "test_fundedBreach_closesAndReturnsToIdle"]),
    ("M6", "src/RuledAccount.sol",
     "CoreOps.setAgent(keyless);",
     "CoreOps.setAgent(old);",
     ["test_breach_cutsAgent_cancels_closes_thenSettles", "test_breach_skipsAKeylessAddressSomeoneActivated"]),
    ("M7", "src/lib/CoreOps.sol",
     "CoreWriterLib.placeLimitOrder(perp, isBuy, px, size1e8, true, Units.TIF_IOC, 0);",
     "CoreWriterLib.placeLimitOrder(perp, isBuy, px, size1e8, false, Units.TIF_IOC, 0);",
     ["test_breach_cutsAgent_cancels_closes_thenSettles"]),
    ("M8", "src/lib/CoreOps.sol",
     "if (!up || down == px) return down;",
     "return down;",
     ["test_btc_integerPartOfFiveDigits_dropsTheDecimal", "test_eth_fourIntegerDigits_keepsFiveSignificant",
      "test_roundingUpCanCarryIntoANewDigit", "test_largeIntegerPart_dropsAllDecimals"]),
    ("M9", "src/ChallengeAccount.sol",
     "if (CoreOps.margin(address(this)).ntlPos != 0) revert NotFlat();",
     "",
     ["test_graduate_needsTargetAndFlat"]),
    ("M10", "src/Pool.sol",
     "address key = factory.registry().assign(trader);",
     "address key = trader; // not a fresh key from the registry",
     ["test_graduate_fundsTraderWithANewKey_andPaysTheShare"]),
    ("M11", "src/KeyRegistry.sol",
     "if (!accounts.isAccount(msg.sender)) revert NotAnAccount(msg.sender);",
     "",
     ["test_assign_onlyAccounts_oneKeyEach"]),
    ("M12", "src/KeyRegistry.sol",
     "if (CoreOps.exists(key)) revert KeyExistsOnCore(key);",
     "",
     ["test_publish_refusesZeroDuplicateAndCoreUsers"]),
    ("M13", "src/ChallengeAccount.sol",
     "        if (payoutOwed != 0 && !payoutDone) {\n            if (spot == 0) return;",
     "        if (false) {\n            if (spot == 0) return;",
     ["test_graduate_fundsTraderWithANewKey_andPaysTheShare"]),
    ("M14", "src/Pool.sol",
     "return (_terms.capital + _terms.fundedCapital) * Units.SPOT_PER_PERP + Units.NEW_ACCOUNT_FEE;",
     "return _terms.capital * Units.SPOT_PER_PERP + Units.NEW_ACCOUNT_FEE;",
     ["test_buyChallenge_needsCapitalForChallengeAndFunding"]),
    ("M15", "src/lib/CoreOps.sol",
     "if (!exists(candidate)) return candidate;",
     "return candidate;",
     ["test_breach_skipsAKeylessAddressSomeoneActivated"]),
    ("M16", "src/Pool.sol",
     "if (challenge != address(0)) revert BadStage(stage);",
     "",
     ["test_noNewChallengeWhileThePassedOneSettles"]),
    ("M17", "src/ChallengeAccount.sol",
     "if (block.timestamp <= createdAt + START_WINDOW) revert TooEarly();",
     "",
     ["test_abort_refundsTheTrader"]),
    ("M18", "src/Pool.sol",
     "        earned += heldPrice;\n        heldPrice = 0;",
     "        heldPrice = 0;",
     ["test_activate_waitsForCapital_thenStarts"]),
    ("M19", "src/RuledAccount.sol",
     "        _cancelAll(cancels);\n        open = _closeAll(extra);",
     "        open = _closeAll(extra);",
     ["test_settle_cancelsNamedOrdersEveryCall"]),
    ("M20", "src/lib/CoreOps.sol",
     "            if (!exists(candidate)) return candidate;\n        }\n    }",
     "            if (!exists(candidate)) return candidate;\n        }\n        revert(\"exhausted\");\n    }",
     ["test_breach_goesThroughEvenIfEveryCandidateWasFunded"]),
    ("M21", "src/ChallengeAccount.sol",
     "if (capitalArrived()) revert CapitalArrived();",
     "",
     ["test_abort_refusedOnceTheCapitalArrived"]),
    ("M22", "src/ChallengeAccount.sol",
     "            return; // the payout hasn't landed yet",
     "",
     ["test_payoutIsSentOnce"]),
    ("M23", "src/ChallengeAccount.sol",
     "            payoutDone = true;\n",
     "",
     ["test_payoutIsSentOnce"]),
    ("M24", "src/RuledAccount.sol",
     "if (block.timestamp % 1 days >= CHECKPOINT_WINDOW) revert OutsideCheckpointWindow();",
     "",
     ["test_checkpoint_onlyJustAfterMidnight"]),
    ("M25", "src/RuledAccount.sol",
     "        if (dayStartEquity > 0) {\n            if (eq * bps < int256(dayStartEquity)",
     "        if (dayStartEquity > 0 && day == _today()) {\n            if (eq * bps < int256(dayStartEquity)",
     ["test_dailyLoss_carriesTheLastSnapshot"]),
    ("M26", "src/RuledAccount.sol",
     "if (!isStopped()) revert NotStopped();",
     "",
     ["test_breach_goesThroughEvenIfEveryCandidateWasFunded"]),
    ("M27", "src/lib/CoreOps.sol",
     "if (szDecimals > 6) revert UnsupportedSizeDecimals(perp, szDecimals);",
     "",
     ["test_close_refusesAnAssetWithTooManySizeDecimals"]),
    ("M28", "src/Pool.sol",
     "            return; // the payout hasn't landed yet",
     "",
     ["test_poolStaysClosingUntilTheFundedPayoutLands"]),
    ("M29", "src/PoolFactory.sol",
     "if ((uint256(t.capital) + t.fundedCapital) * Units.SPOT_PER_PERP + Units.NEW_ACCOUNT_FEE > type(uint64).max) {",
     "if (false) {",
     ["test_createPool_refusesCapitalThatCannotBeHeldOnSpot"]),
    ("M30", "src/RuledAccount.sol",
     "        if (notional != 0) {\n            emit UnnamedPositionOpen(notional);",
     "        if (false) {\n            emit UnnamedPositionOpen(notional);",
     ["test_settle_waitsWhileAnUnnamedPositionIsOpen"]),
    ("M31", "src/Pool.sol",
     "            int64 result = CoreOps.equity(address(this));",
     "            int64 result = fundedStopEquity;",
     ["test_fundedShare_comesFromWhatClosingRealized"]),
    ("M32", "src/Pool.sol",
     "            fundedResultTaken = true;\n",
     "",
     ["test_poolStaysClosingUntilTheFundedPayoutLands"]),
    ("M33", "src/Pool.sol",
     "            usdc.safeTransferFrom(msg.sender, recipient, fee);",
     "",
     ["test_buyChallenge_paysThePlatformFee_whichAnAbortKeeps"]),
    ("M34", "src/PoolFactory.sol",
     "        if (fee != 0 && recipient == address(0)) revert BadFee();",
     "",
     ["test_setChallengeFee_operatorOnly_andNeedsARecipient"]),
    ("M35", "src/Pool.sol",
     "* Units.SPOT_PER_PERP + Units.NEW_ACCOUNT_FEE;",
     "* Units.SPOT_PER_PERP;",
     ["test_buyChallenge_needsCapitalForChallengeAndFunding"]),
    ("M36", "src/RuledAccount.sol",
     "            cutKey = old;",
     "",
     ["test_breach_cutsAgent_cancels_closes_thenSettles", "test_recut_keepsTheCutKeyOnRecord"]),
    ("M37", "src/RuledAccount.sol",
     "        cutBlock = uint64(block.number);\n        if (old != address(0)) {\n            cutKey = old;",
     "        cutBlock = uint64(block.number);\n        cutKey = old;\n        if (old != address(0)) {",
     ["test_recut_keepsTheCutKeyOnRecord"]),
    ("M38", "src/RuledAccount.sol",
     "        cutBlock = uint64(block.number);",
     "        if (cutBlock == 0) cutBlock = uint64(block.number);",
     ["test_recut_keepsTheCutKeyOnRecord"]),
    ("M39", "src/PoolFactory.sol",
     "* Units.SPOT_PER_PERP + Units.NEW_ACCOUNT_FEE > type(uint64).max) {",
     "* Units.SPOT_PER_PERP > type(uint64).max) {",
     ["test_createPool_refusesCapitalThatCannotBeHeldOnSpot"]),
    ("M40", "src/lib/CoreOps.sol",
     "        if (exists(to)) return budget1e8;",
     "        return budget1e8;",
     ["test_payout_toATraderWithoutAnAccount_coversTheFeeFromTheShare",
      "test_payout_smallerThanTheAccountFee_isNotSent",
      "test_fundedPayout_toATraderWithoutAnAccount_coversTheFee"]),
    ("M41", "src/lib/CoreOps.sol",
     "? budget1e8 - Units.NEW_ACCOUNT_FEE : 0;",
     "? budget1e8 - Units.NEW_ACCOUNT_FEE : budget1e8;",
     ["test_payout_smallerThanTheAccountFee_isNotSent"]),
    ("M42", "src/Pool.sol",
     "uint64 pay = CoreOps.sendableTo(fundedTrader, spot < fundedPayoutOwed ? spot : fundedPayoutOwed);",
     "uint64 pay = spot < fundedPayoutOwed ? spot : fundedPayoutOwed;",
     ["test_fundedPayout_toATraderWithoutAnAccount_coversTheFee"]),
    ("M43", "src/Pool.sol",
     "            fundedPayoutDone = true;\n",
     "",
     ["test_poolStaysClosingUntilTheFundedPayoutLands"]),
    ("M44", "src/ChallengeAccount.sol",
     "uint64 pay = CoreOps.sendableTo(trader, spot < payoutOwed ? spot : payoutOwed);",
     "uint64 pay = spot < payoutOwed ? spot : payoutOwed;",
     ["test_payout_toATraderWithoutAnAccount_coversTheFeeFromTheShare"]),
    ("M45", "src/Pool.sol",
     "    function capitalNeeded() public view returns (uint64) {",
     "    function deposit(uint256) external {}\n\n    function capitalNeeded() public view returns (uint64) {",
     ["test_capitalOnlyArrivesOnCore"]),
    ("M46", "src/KeyRegistry.sol",
     "key = _free[_free.length - 1];\n            if (!CoreOps.exists(key)) break;\n            if (skipped",
     "key = _free[_free.length - 1];\n            break;\n            if (skipped",
     ["test_assign_skipsAKeyThatGotAnAccount"]),
    ("M47", "src/KeyRegistry.sol",
     "            if (skipped == MAX_SPOILED_SKIPS) revert TooManySpoiledKeys();\n",
     "",
     ["test_manySpoiledKeys_arePurgedByAnyone"]),
    ("M48", "src/KeyRegistry.sol",
     "            if (!CoreOps.exists(key)) break;\n            _free.pop();\n            _spoil(key);\n            ++purged;",
     "            _free.pop();\n            _spoil(key);\n            ++purged;",
     ["test_manySpoiledKeys_arePurgedByAnyone"]),
    ("M49", "src/ChallengeAccount.sol",
     "        if (CoreOps.exists(agentKey)) revert KeySpoiled();\n",
     "",
     ["test_aSpoiledKey_blocksTheStart_andAbortRefunds"]),
    ("M50", "src/ChallengeAccount.sol",
     "        if (!keySpoiled()) {",
     "        if (true) {",
     ["test_aSpoiledKey_blocksTheStart_andAbortRefunds"]),
    ("M51", "src/ChallengeAccount.sol",
     "payoutOwed = SafeCast.toUint64((profit * _terms.traderShareChallengeBps * Units.SPOT_PER_PERP) / Units.BPS);",
     "payoutOwed = SafeCast.toUint64((profit * _terms.traderShareFundedBps * Units.SPOT_PER_PERP) / Units.BPS);",
     ["test_shares_areIndependent_zeroOnTheChallenge_eightyOnTheFunded",
      "test_graduate_fundsTraderWithANewKey_andPaysTheShare"]),
    ("M52", "src/Pool.sol",
     "* _terms.traderShareFundedBps * Units.SPOT_PER_PERP)",
     "* _terms.traderShareChallengeBps * Units.SPOT_PER_PERP)",
     ["test_shares_areIndependent_eightyOnTheChallenge_zeroOnTheFunded",
      "test_fundedShare_comesFromWhatClosingRealized"]),
    ("M53", "src/PoolFactory.sol",
     "        if (t.price == 0) revert BadTerms();",
     "",
     ["test_createPool_checksRulesAndTerms"]),
    ("M54", "src/PoolFactory.sol",
     "if (t.traderShareChallengeBps > Units.BPS || t.traderShareFundedBps > Units.BPS) revert BadTerms();",
     "if (t.traderShareChallengeBps > Units.BPS) revert BadTerms();",
     ["test_createPool_checksRulesAndTerms"]),
    # ── gateway (Python unittest) ──
    # P: the shared pool (src/shared), guarded by test/shared.
    ("P1", "src/shared/SharedPool.sol",
     "_mint(platform, seed);",
     "_mint(operator, seed);",
     ["test_start_turnsTheSeedIntoThePlatformsShares_once"]),
    ("P2", "src/shared/SharedPool.sol",
     "if (seedValue * Units.BPS < plan * SEED_BPS)",
     "if (seedValue * Units.BPS <= plan * SEED_BPS)",
     ["test_addSeat_keepsTheSeedAtFivePercentOfThePlan"]),
    ("P3", "src/shared/SharedPool.sol",
     "uint256 minted = (uint256(amount) * sharesBefore) / poolValue;",
     "uint256 minted = (uint256(amount) * totalShares) / poolValue;",
     ["test_settle_pricesDepositsAtTheValueWithoutThem_allAtOnePrice"]),
    ("P4", "src/shared/SharedPool.sol",
     "            if (amount < minDeposit) continue;\n",
     "",
     ["test_settle_takesATicketOnlyFromTheMinimum"]),
    ("P5", "src/shared/SharedPool.sol",
     "v += int256(uint256(CoreOps.spotUsdc(_closed[i])));",
     "v += 0;",
     ["test_closedTicket_countsUntilItsMoneyLands_thenIsForgotten"]),
    ("P6", "src/shared/SharedPool.sol",
     "            tk.state = TicketState.Closed;\n",
     "",
     ["test_ticketIsRecognizedOnce"]),
    ("P7", "src/shared/DepositTicket.sol",
     "if (msg.sender != pool) revert NotPool();",
     "",
     ["test_ticket_isKnownBeforehand_andPaysOnlyIntoItsPool"]),
    ("P8", "src/shared/SharedPool.sol",
     "v -= _share(eq - int256(p.fundedStart()), t.shareFundedBps);",
     "v -= 0;",
     ["test_value_leavesOutTheTradersShareOfAFundedProfit"]),
    ("P9", "src/shared/SharedPool.sol",
     "if (!c.payoutDone()) v -= int256(uint256(c.payoutOwed()));",
     "if (!c.payoutDone()) v -= 0;",
     ["test_value_leavesOutAPassedChallengesUnpaidShare"]),
    ("P10", "src/shared/SharedPool.sol",
     "if (c.violation(none) != Breach.None) return (Blocker.RuleBroken, ch);",
     "",
     ["test_settle_waitsWhileAChallengeBreaksARule"]),
    ("P11", "src/shared/SharedPool.sol",
     "if (CoreOps.margin(ch).ntlPos != 0) return (Blocker.PositionsOpen, ch);",
     "",
     ["test_settle_waitsWhileAStoppedChallengeHoldsPositions"]),
    ("P12", "src/shared/SharedPool.sol",
     "if (st == Pool.Stage.Closing) return (Blocker.SeatClosing, address(p));",
     "",
     ["test_settle_waitsWhileASeatCloses"]),
    ("P13", "src/shared/SharedPool.sol",
     "if (c.payoutDone() && _payoutLanding(c)) return (Blocker.PayoutInFlight, ch);",
     "",
     ["test_settle_waitsWhileAPayoutIsInFlight"]),
    ("P14", "src/shared/SharedPool.sol",
     "if (reason != Blocker.None) revert NotQuiet(reason, account);",
     "",
     ["test_settle_waitsWhileAChallengeBreaksARule", "test_settle_waitsWhileASeatCloses"]),
    ("P15", "src/shared/SharedPool.sol",
     "uint64 cost = CoreOps.exists(seat) ? amount : amount + Units.NEW_ACCOUNT_FEE;",
     "uint64 cost = amount;",
     ["test_armSeat_refusesWithoutRoomForTheAccountFee"]),
    ("P16", "src/shared/SharedPool.sol",
     "if (armedAt[seat] != 0 && block.timestamp <= armedAt[seat] + ARM_WAIT) revert TooSoon(seat);",
     "",
     ["test_armSeat_waitsForThePreviousTopUp"]),
    ("P17", "src/shared/SharedPool.sol",
     "+ int256(p.earned() * Units.SPOT_PER_PERP);",
     ";",
     ["test_value_countsSeatsChallengesAndPricesOnBothSides"]),
    ("P18", "src/shared/SharedPool.sol",
     "v += int256(usdc.balanceOf(address(this)) * Units.SPOT_PER_PERP);",
     "",
     ["test_value_countsSeatsChallengesAndPricesOnBothSides"]),
    ("P19", "src/shared/SharedPool.sol",
     "if (st == Pool.Stage.Funded && p.violation(none) != Breach.None) return (Blocker.RuleBroken, address(p));",
     "",
     ["test_settle_waitsWhileAFundedSeatBreaksARule"]),
    ("P20", "src/shared/SharedPool.sol",
     "if (eq >= target) v -= _share(eq - capital, t.shareChallengeBps);",
     "if (eq >= target) v -= 0;",
     ["test_value_leavesOutTheTradersShareOfAChallengeAtItsTarget"]),
    ("P21", "src/shared/SharedPool.sol",
     "if (p.stage() != Pool.Stage.Idle || p.challenge() != address(0)) revert SeatBusy(seat);\n        // The previous top-up",
     "// The previous top-up",
     ["test_armSeat_onlyAnIdleSeat"]),
    ("P22", "src/shared/SharedPool.sol",
     "if (_closedSlot[t] == 0) _addClosed(t);",
     "",
     ["test_strayMoneyOnAForgottenTicket_isTakenIn"]),
    ("P23", "src/shared/SharedPool.sol",
     "return CoreOps.spotUsdc(address(c)) + c.payoutSent() > c.payoutSpotBefore()",
     "return CoreOps.spotUsdc(address(c)) + c.payoutSent() >= c.payoutSpotBefore()",
     ["test_settle_waitsWhileAPayoutIsInFlight"]),
    ("P24", "src/shared/SharedPool.sol",
     "        if (profit1e6 <= 0) return 0;\n",
     "",
     ["test_value_leavesOutTheTradersShareOfAFundedProfit"]),
    ("P25", "src/shared/SharedPool.sol",
     "if (held < SWEEP_MIN) {",
     "if (held == 0) {",
     ["test_dustOnAClosedTicket_isForgotten"]),
    ("P26", "src/shared/SharedPool.sol",
     "if (minDeposit_ < SWEEP_MIN) revert BadDeposit();",
     "if (minDeposit_ == 0) revert BadDeposit();",
     ["test_minimumDeposit_isAtLeastWhatASweepTakes"]),
    ("P27", "src/shared/SharedPool.sol",
     "if (block.timestamp < until) revert Locked(until);",
     "",
     ["test_requestRedeem_onlyFreeShares_afterTheLock_neverTheSeed"]),
    ("P28", "src/shared/SharedPool.sol",
     "uint256 held = queuedOf[msg.sender] + (msg.sender == platform ? seedShares : 0);",
     "uint256 held = queuedOf[msg.sender];",
     ["test_requestRedeem_onlyFreeShares_afterTheLock_neverTheSeed"]),
    ("P29", "src/shared/SharedPool.sol",
     "uint256 gross = (s * poolValue) / sharesBefore;",
     "uint256 gross = (s * poolValue) / totalShares;",
     ["test_depositAndPaymentInOnePoint_shareOnePrice"]),
    ("P30", "src/shared/SharedPool.sol",
     "uint256 fromEvm6 = evm6 < wanted6 ? evm6 : wanted6;",
     "uint256 fromEvm6 = 0;",
     ["test_settle_paysTheQueueInFull_evmFirst_atThePointsPrice"]),
    ("P31", "src/shared/SharedPool.sol",
     "if (h != platform && gross > cost) {",
     "if (h != platform) {",
     ["test_queuedShares_bearTheResultUntilPaid_noFeeOnALoss"]),
    ("P32", "src/shared/SharedPool.sol",
     "uint256 cost = (basis[h] * s) / sharesOf[h];",
     "uint256 cost = s;",
     ["test_fee_isOnEachHoldersOwnProfit"]),
    ("P33", "src/shared/SharedPool.sol",
     "uint256 s = (queuedOf[h] * num) / den;",
     "uint256 s = queuedOf[h];",
     ["test_settle_paysEveryRequestTheSameFraction_whenMoneyIsShort"]),
    ("P34", "src/shared/SharedPool.sol",
     "net6[k] = ((s - f) * poolValue) / sharesBefore / Units.SPOT_PER_PERP;",
     "net6[k] = (s - f) / Units.SPOT_PER_PERP;",
     ["test_queuedShares_bearTheResultUntilPaid_noFeeOnALoss"]),
    ("P35", "src/shared/SharedPool.sol",
     "if (left < _queuedValue()) revert QueueWaiting();",
     "",
     ["test_armSeat_onlyFromMoneyTheQueueDoesntNeed"]),
    ("P36", "src/shared/SharedPool.sol",
     "        _paymentsLanded();\n",
     "",
     ["test_ownPayments_holdUpTheNextPointAndTopUps"]),
    ("P37", "src/shared/SharedPool.sol",
     "if (queuedShares == 0) revert NoQueue();",
     "",
     ["test_releaseSeat_bringsAnIdleSeatsCapitalBack_whileTheQueueWaits"]),
    ("P38", "src/shared/SharedPool.sol",
     "            return (Blocker.PaymentInFlight, address(this));\n",
     "",
     ["test_ownPayments_holdUpTheNextPointAndTopUps"]),
    ("P39", "src/shared/SharedPool.sol",
     "if (core) lastCorePayAt = uint64(block.timestamp);",
     "",
     ["test_ownPayments_holdUpTheNextPointAndTopUps"]),
    ("P40", "src/shared/SharedPool.sol",
     "if (block.timestamp < until) revert TermNotOver(until);",
     "",
     ["test_endFundedTerm_onlyAfterItsTerm"]),
    ("P41", "src/shared/SharedPool.sol",
     "if (fundedSince[seat] == 0 || fundedKey[seat] != key) {",
     "if (fundedSince[seat] == 0) {",
     ["test_noteFunded_tellsANewStageFromTheOldOne"]),
    ("P42", "src/shared/SharedPool.sol",
     "            basis[tk.depositor] += amount;\n",
     "",
     ["test_settle_paysTheQueueInFull_evmFirst_atThePointsPrice"]),
    ("P43", "src/shared/SharedPool.sol",
     "            lastDeposit[tk.depositor] = uint64(block.timestamp);\n",
     "",
     ["test_requestRedeem_onlyFreeShares_afterTheLock_neverTheSeed"]),
    ("P44", "src/shared/SharedPool.sol",
     "        sharesOf[platform] += fee;\n",
     "",
     ["test_settle_paysTheQueueInFull_evmFirst_atThePointsPrice"]),
    ("P45", "src/shared/SharedPool.sol",
     "if (Pool(_seats[i]).earned() != 0) Pool(_seats[i]).withdrawEarned();",
     "",
     ["test_settle_paysEveryRequestTheSameFraction_whenMoneyIsShort"]),
    ("P46", "src/shared/SharedPool.sol",
     "            if (queuedOf[h] == 0) _dropQueue(h);\n",
     "",
     ["test_settle_paysTheQueueInFull_evmFirst_atThePointsPrice"]),
    ("P47", "src/shared/SharedPool.sol",
     "sent = CoreOps.sendableTo(h, core1e8);",
     "sent = core1e8;",
     ["test_aHolderWithoutACoreAccount_paysItsCreation"]),
    ("P48", "src/shared/SharedPool.sol",
     "if (fundedTerm_ == 0) revert BadTerm();",
     "",
     ["test_addSeat_needsAFundedTerm"]),
    ("P49", "src/shared/SharedPool.sol",
     "if (feeBps_ > Units.BPS) revert BadFee();",
     "",
     ["test_constructor_refusesAFeeAboveTheWholeProfit"]),
    ("P50", "src/shared/SharedPool.sol",
     "            if (fundedSince[seat] != 0) {\n                fundedSince[seat] = 0;\n                fundedKey[seat] = address(0);\n            }\n",
     "",
     ["test_noteFunded_tellsANewStageFromTheOldOne"]),
    ("P51", "src/shared/SharedPool.sol",
     "if (p.stage() != Pool.Stage.Idle || p.challenge() != address(0)) revert SeatBusy(seat);\n        uint64 held",
     "uint64 held",
     ["test_releaseSeat_onlyAnIdleSeat"]),
    ("P52", "src/shared/SharedPool.sol",
     "if (lastArmAt != 0 && block.timestamp <= lastArmAt + ARM_WAIT) return;",
     "",
     ["test_noPayment_whileATopUpIsInFlight"]),
    ("P53", "src/shared/SharedPool.sol",
     "            if (net6[k] != 0) continue;\n",
     "            continue;\n",
     ["test_dustRequest_isClearedAtThePoint"]),
    ("P54", "src/shared/SharedPool.sol",
     "if (free >= _queuedValue()) revert QueueCovered();",
     "",
     ["test_releaseSeat_bringsAnIdleSeatsCapitalBack_whileTheQueueWaits"]),
    ("P55", "src/shared/SharedPool.sol",
     "        lastArmAt = uint64(block.timestamp);\n",
     "",
     ["test_noPayment_whileATopUpIsInFlight"]),
    ("P56", "src/shared/SharedPool.sol",
     "        p.evm += SafeCast.toUint96(evm6);\n",
     "",
     ["test_settle_paysTheQueueInFull_evmFirst_atThePointsPrice", "test_payments_addUpAcrossPoints_eachPartApart"]),
    ("P57", "src/shared/SharedPool.sol",
     "        p.evm += SafeCast.toUint96(evm6);\n",
     "        p.evm = SafeCast.toUint96(evm6);\n",
     ["test_payments_addUpAcrossPoints_eachPartApart"]),
    ("P58", "src/shared/SharedPool.sol",
     "        p.core += sent;\n",
     "        p.core += core1e8;\n",
     ["test_aHolderWithoutACoreAccount_paysItsCreation"]),
    ("P59", "src/shared/SharedPool.sol",
     "        p.core += sent;\n",
     "        p.core = sent;\n",
     ["test_payments_addUpAcrossPoints_eachPartApart"]),
    ("P60", "src/shared/SharedPool.sol",
     "        p.at = uint64(block.timestamp);\n",
     "",
     ["test_settle_paysTheQueueInFull_evmFirst_atThePointsPrice", "test_aHolderWithoutACoreAccount_paysItsCreation",
      "test_payments_addUpAcrossPoints_eachPartApart"]),
    ("P61", "src/shared/SharedPool.sol",
     "        if (evm6 == 0 && sent == 0) return onCore;\n",
     "",
     ["test_payments_noteNothing_whenNothingIsSent"]),
    ("G1", "gateway/server.py",
     "if recovered.lower() != cleared.key.lower():",
     "if False:",
     ["test_wrong_signing_key_is_never_submitted"]),
    ("G2", "gateway/checks.py",
     "if not reader.is_bound(key, req.account, trader):",
     "if False:",
     ["test_someone_elses_signature", "test_changed_field_is_not_the_traders",
      "test_order_signature_is_not_a_cancel_signature"]),
    ("G3", "gateway/checks.py",
     "if not nonces.claim(trader, req.nonce, req.expires_at, now_ms):",
     "if False:",
     ["test_replay"]),
    ("G4", "gateway/checks.py",
     "if not now_ms < req.expires_at <= now_ms + MAX_EXPIRY_MS:",
     "if False:",
     ["test_expiry_window"]),
    ("G5", "gateway/checks.py",
     "if req.asset not in reader.allowed_assets(req.account):",
     "if False:",
     ["test_asset_outside_the_rules"]),
    ("G6", "gateway/checks.py",
     "if set(fields) != expected:",
     "if False:",
     ["test_shape"]),
    ("G7", "gateway/hl.py",
     "return action_hash(action, None, nonce, None)",
     "return action_hash(action, None, nonce + 1, None)",
     ["test_action_hash_matches_the_sdk_production_vector"]),
    ("G8", "gateway/checks.py",
     'DECIMAL = re.compile(r"^(0|[1-9][0-9]{0,15})(\\.[0-9]{0,9}[1-9])?$")',
     'DECIMAL = re.compile(r"^[0-9.]+$")',
     ["test_shape"]),
    ("G10", "app/lib/gateway.js",
     '    { name: "limitPx", type: "string" },\n    { name: "size", type: "string" },',
     '    { name: "size", type: "string" },\n    { name: "limitPx", type: "string" },',
     ["test_types_and_domain_match"]),
    ("G9", "gateway/checks.py",
     '"a": m["asset"], "b": m["isBuy"], "p": m["limitPx"], "s": m["size"],\n                    "r": m["reduceOnly"],',
     '"a": m["asset"], "b": m["isBuy"], "s": m["size"], "p": m["limitPx"],\n                    "r": m["reduceOnly"],',
     ["test_built_action_is_the_sdk_vector"]),
    ("G11", "gateway/checks.py",
     "while self._by_expiry and self._by_expiry[0][0] <= now_ms:",
     "while False:",
     ["test_forgets_only_expired_entries", "test_is_bounded"]),
    ("G12", "gateway/checks.py",
     "if len(self._seen) >= self._limit:",
     "if False:",
     ["test_is_bounded"]),
    ("G13", "gateway/server.py",
     "timeout = request_timeout  # applies to every read and write on the connection",
     "timeout = None",
     ["test_a_silent_client_is_dropped"]),
    ("G14", "gateway/server.py",
     "if not self._slots.acquire(blocking=False):",
     "if False:",
     ["test_busy_server_answers_503_and_frees_the_slot"]),
    ("G15", "gateway/server.py",
     "        if signature is None:\n            return None, 502,",
     "        if False:\n            return None, 502,",
     ["test_malformed_enclave_signature_is_never_submitted"]),
    ("G16", "gateway/server.py",
     "except Exception as e:  # a chain read or the Signer failed; nothing was submitted",
     "except ZeroDivisionError as e:",
     ["test_upstream_failure_is_an_answer_not_a_crash"]),
    ("G17", "gateway/server.py",
     '"signer": signer_reason(signed.body),',
     '"signer": signed.body,',
     ["test_enclave_refusal_passes_on_only_the_reason"]),
    ("G18", "gateway/server.py",
     "            except ValueError:\n                length = -1",
     "            except ValueError:\n                raise",
     ["test_bad_content_length"]),
    ("G19", "gateway/server.py",
     "            venue = self.submit(req.action(), req.nonce, signature)\n        except Exception as e:",
     "            venue = self.submit(req.action(), req.nonce, signature)\n        except ZeroDivisionError as e:",
     ["test_unreachable_venue_is_reported_with_the_receipt"]),
    ("G20", "gateway/server.py",
     "    if type(v) is not int or v not in (27, 28):",
     "    if v not in (27, 28):",
     ["test_malformed_enclave_signature_is_never_submitted"]),
    ("G21", "gateway/server.py",
     "        if signature is None:\n            self.nonces.release(cleared.trader, req.nonce)\n",
     "        if signature is None:\n",
     ["test_a_request_that_never_reached_the_venue_can_be_retried"]),
    ("G22", "gateway/server.py",
     "        except BaseException:\n            self.nonces.release(cleared.trader, req.nonce)\n            raise",
     "        except BaseException:\n            raise",
     ["test_a_request_that_never_reached_the_venue_can_be_retried"]),
    ("G23", "gateway/server.py",
     "        try:\n            signature, status, payload = self._sign(req, cleared)",
     "        self.nonces.release(cleared.trader, req.nonce)\n        try:\n            signature, status, payload = self._sign(req, cleared)",
     ["test_a_copy_arriving_while_the_first_is_being_signed_is_refused",
      "test_a_request_that_may_have_reached_the_venue_keeps_its_nonce"]),
    ("G24", "app/config.js",
     "  chainId: 998,",
     "  chainId: 999,",
     ["test_types_and_domain_match"]),
    ("G25", "app/lib/gateway.js",
     'const DOMAIN = { name: "colosseum-pools gateway", version: "2", chainId: CONFIG.chainId };',
     'const DOMAIN = { name: "colosseum-pools gateway", version: "2", chainId: CONFIG.chainId, verifyingContract: CONFIG.factory };',
     ["test_types_and_domain_match"]),
    ("G26", "gateway/server.py",
     "        if refusal is not None:\n            return 422,",
     "        if False:\n            return 422,",
     ["test_what_hyperliquid_answered_decides_the_status"]),
    ("G27", "gateway/hl.py",
     "        if isinstance(status, dict) and \"error\" in status:",
     "        if False:",
     ["test_what_hyperliquid_answered_decides_the_status"]),
    ("G28", "gateway/server.py",
     "        if not confirmed:\n            return 502,",
     "        if False:\n            return 502,",
     ["test_what_hyperliquid_answered_decides_the_status"]),
    ("G29", "gateway/checks.py",
     "                if self._seen.get(old) == expired:",
     "                if True:",
     ["test_a_pair_given_back_and_claimed_again_stays_guarded_until_its_own_expiry"]),
    ("G30", "gateway/hl.py",
     "    return None, all(_confirmed(status) for status in statuses)",
     "    return None, True",
     ["test_what_hyperliquid_answered_decides_the_status"]),
    ("G31", "gateway/hl.py",
     "isinstance(status.get(outcome), dict) for outcome in",
     "outcome in status for outcome in",
     ["test_what_hyperliquid_answered_decides_the_status"]),
    ("G32", "gateway/hl.py",
     "    return status == \"success\" or (",
     "    return isinstance(status, str) or (",
     ["test_what_hyperliquid_answered_decides_the_status"]),
    ("G33", "gateway/chain.py",
     "            if resp.status_code != 429:",
     "            if True:",
     ["test_a_throttled_read_is_retried_briefly", "test_it_gives_up_in_the_end_and_says_it_was_throttled"]),
    ("G34", "gateway/chain.py",
     "                if not (isinstance(error, dict) and error.get(\"code\") == RATE_LIMITED):",
     "                if True:",
     ["test_a_throttled_read_is_retried_briefly", "test_it_gives_up_in_the_end_and_says_it_was_throttled"]),
    ("G59", "gateway/server.py",
     "        except Throttled:",
     "        except NotImplementedError:",
     ["test_a_throttled_node_is_busy_not_broken"]),
    ("G60", "gateway/chain.py",
     '        raise Throttled(f"{method}: rate limited {RPC_ATTEMPTS} times in a row")',
     '        raise RuntimeError(f"{method}: rate limited {RPC_ATTEMPTS} times in a row")',
     ["test_it_gives_up_in_the_end_and_says_it_was_throttled"]),
    ("G35", "gateway/chain.py",
     "RPC_ATTEMPTS = 5",
     "RPC_ATTEMPTS = 1",
     ["test_a_throttled_read_is_retried_briefly"]),
    ("G36", "gateway/chain.py",
     "                delay *= 2",
     "",
     ["test_a_throttled_read_is_retried_briefly"]),
    ("G37", "gateway/demo_signer.py",
     "    if size > MAX_SIZE[asset]:",
     "    if False:",
     ["test_each_asset_has_its_size_cap", "test_over_the_cap_is_refused_before_signing_and_the_nonce_comes_back"]),
    ("G38", "gateway/demo_signer.py",
     "    if size * highest > MAX_NOTIONAL:",
     "    if False:",
     ["test_notional_cap", "test_a_sell_under_the_market_counts_at_the_mid",
      "test_a_sell_under_the_market_over_the_cap_is_refused_before_signing"]),
    ("G39", "gateway/demo_signer.py",
     "    if asset not in MAX_SIZE:",
     "    if False:",
     ["test_only_listed_assets"]),
    ("G40", "gateway/demo_signer.py",
     "isinstance(t, dict) and set(t) == {\"limit\"} and ",
     "isinstance(t, dict) and ",
     ["test_one_limit_order_or_one_cancel_only"]),
    ("G41", "gateway/demo_signer.py",
     "        if d.stat().st_mode & 0o077:",
     "        if False:",
     ["test_loose_permissions_or_no_keys_refuse_to_start"]),
    ("G42", "gateway/demo_signer.py",
     "            if f.stat().st_mode & 0o077:",
     "            if False:",
     ["test_loose_permissions_or_no_keys_refuse_to_start"]),
    ("G43", "gateway/demo_signer.py",
     "        check_caps(kind, action, self._mid)\n",
     "",
     ["test_nothing_over_the_caps_is_signed", "test_over_the_cap_is_refused_before_signing_and_the_nonce_comes_back"]),
    ("G44", "gateway/server.py",
     '    raise SystemExit("GATEWAY_SIGNER must be demo or signer")',
     '    return "demo", DemoSigner([])',
     ["test_the_mode_is_chosen_explicitly"]),
    ("G45", "gateway/demo_signer.py",
     "        if cancels[0].get(\"a\") not in MAX_SIZE:",
     "        if False:",
     ["test_only_listed_assets"]),
    # The hole of 17 Sep: a sell counted at its limit, while it fills at the market.
    ("G46", "gateway/demo_signer.py",
     "    highest = price if order.get(\"b\") is True else max(price, mid(asset))",
     "    highest = price",
     ["test_a_sell_under_the_market_counts_at_the_mid", "test_only_a_literal_true_is_a_buy",
      "test_a_sell_under_the_market_over_the_cap_is_refused_before_signing"]),
    ("G47", "gateway/demo_signer.py",
     "    highest = price if order.get(\"b\") is True else max(price, mid(asset))",
     "    highest = price if order.get(\"b\") is True else mid(asset)",
     ["test_a_sell_over_the_market_counts_at_its_limit"]),
    ("G48", "gateway/demo_signer.py",
     "    highest = price if order.get(\"b\") is True else max(price, mid(asset))",
     "    highest = max(price, mid(asset))",
     ["test_a_buy_counts_at_its_limit_and_never_reads_the_market", "test_notional_cap",
      "test_a_sell_is_not_signed_without_a_mid"]),
    ("G49", "gateway/demo_signer.py",
     "    highest = price if order.get(\"b\") is True else max(price, mid(asset))",
     "    highest = price if order.get(\"b\") else max(price, mid(asset))",
     ["test_only_a_literal_true_is_a_buy"]),
    ("G50", "gateway/demo_signer.py",
     "    if mid is None:\n        raise GatewayError(502, \"no_market_price\"",
     "    if False:\n        raise GatewayError(502, \"no_market_price\"",
     ["test_the_mid_is_hyperliquids"]),
    ("G51", "gateway/demo_signer.py",
     "    def __init__(self, keys: list[LocalAccount], mid: Callable[[int], Decimal] = market_mid):",
     "    def __init__(self, keys: list[LocalAccount], mid: Callable[[int], Decimal] = lambda asset: Decimal(1)):",
     ["test_the_mid_is_hyperliquids"]),
    ("G52", "gateway/demo_signer.py",
     "        check_caps(kind, action, self._mid)",
     "        check_caps(kind, action, lambda asset: Decimal(1))",
     ["test_a_sell_under_the_market_over_the_cap_is_refused_before_signing"]),
    ("G53", "gateway/hl.py",
     'TESTNET_INFO_URL = "https://api.hyperliquid-testnet.xyz/info"',
     'TESTNET_INFO_URL = "https://api.hyperliquid.xyz/info"',
     ["test_mids_come_from_the_testnet_info_api"]),
    # Reduce-only passes the notional cap only (CTO, 18 Sep 2026).
    ("G54", "gateway/demo_signer.py",
     '    if order.get("r") is True:\n        return\n',
     '    if False:\n        return\n',
     ["test_reduce_only_passes_the_notional_cap_and_nothing_else",
      "test_reduce_only_over_the_notional_is_signed_the_same_order_without_it_is_not"]),
    ("G55", "gateway/demo_signer.py",
     '    if order.get("r") is True:\n        return\n',
     '    if order.get("r"):\n        return\n',
     ["test_reduce_only_passes_the_notional_cap_and_nothing_else"]),
    ("G56", "gateway/demo_signer.py",
     "    if size > MAX_SIZE[asset]:",
     '    if size > MAX_SIZE[asset] and order.get("r") is not True:',
     ["test_reduce_only_passes_the_notional_cap_and_nothing_else"]),
    ("G57", "gateway/demo_signer.py",
     "    if asset not in MAX_SIZE:",
     '    if asset not in MAX_SIZE and order.get("r") is not True:',
     ["test_reduce_only_passes_the_notional_cap_and_nothing_else"]),
    ("G58", "gateway/demo_signer.py",
     '        raise GatewayError(403, "policy", "limit orders only")',
     '        if order.get("r") is not True: raise GatewayError(403, "policy", "limit orders only")',
     ["test_reduce_only_passes_the_notional_cap_and_nothing_else"]),
    # ── agent client (Python unittest) ──
    ("A1", "agents/client.py",
     "nonce = max(int(time.time() * 1000), self._last_nonce + 1)",
     "nonce = int(time.time() * 1000)",
     ["test_nonces_never_repeat_within_a_millisecond"]),
    ("A2", "agents/client.py",
     "size = int(sz * factor + 1e-9) / factor",
     "size = round(sz * factor) / factor",
     ["test_sizes"]),
    ("A3", "agents/client.py",
     "return str(math.floor(px + 0.5))",
     "return str(round(px))",
     ["test_prices"]),
    ("A4", "agents/client.py",
     '"reduceOnly": reduce_only, "tif": tif,',
     '"reduceOnly": False, "tif": tif,',
     ["test_reduce_only_reaches_the_action"]),
    ("A5", "agents/client.py",
     '"signature": auth.sign(self.wallet, kind, fields)}',
     '"signature": auth.sign(self.wallet, "order", fields)}',
     ["test_cancel_clears_every_gateway_check"]),
    ("A6", "agents/client.py",
     "    if parts.scheme != \"https\" and not local:",
     "    if False:",
     ["test_https_unless_the_gateway_runs_here"]),
    ("A22", "agents/client.py",
     '    return parts._replace(path=parts.path.rstrip("/") + "/v1/order", query="", fragment="").geturl()',
     '    return base.rstrip("/") + "/v1/order"',
     ["test_https_unless_the_gateway_runs_here"]),
    ("A24", "agents/client.py",
     "    load_counters(d, DESK_COUNTERS, path)",
     "    pass",
     ["test_orders_are_counted_across_commands_and_days"]),
    ("A25", "agents/client.py",
     "-{subject.lower()}-{day}.json",
     "-{subject.lower()}.json",
     ["test_orders_are_counted_across_commands_and_days"]),
    ("A26", "agents/client.py",
     "setattr(obj, name, min(int(saved[name]), getattr(obj, name)))",
     "setattr(obj, name, int(saved[name]))",
     ["test_a_counter_file_can_lower_the_limits_but_not_raise_them"]),
    ("A27", "agents/client.py",
     "        if not reader.is_bound(key, args.account, wallet.address):",
     "        if False:",
     ["test_a_wallet_that_is_not_the_accounts_trader_sends_nothing"]),
    ("A28", "agents/client.py",
     "wallet = chain.account(args.wallet) if send and acts else None",
     "wallet = chain.account(args.wallet) if send else None",
     ["test_reads_and_dry_runs_load_no_key_and_send_nothing"]),
    ("A29", "agents/client.py",
     "WINDOW_MAX_ORDER_USDC = 100.0",
     "WINDOW_MAX_ORDER_USDC = 1000.0",
     ["test_the_per_order_cap_is_the_windows"]),
    ("A23", "agents/ai_trader.py",
     "    except Refused as exc:\n        raise ToolError(str(exc)) from None",
     "    except ZeroDivisionError as exc:\n        raise ToolError(str(exc)) from None",
     ["test_a_desk_refusal_reaches_the_model_as_a_tool_error"]),
    ("A7", "agents/desk.py",
     "            if notional > self.limits.max_notional:",
     "            if False:",
     ["test_minimum_and_per_order_cap"]),
    ("A8", "agents/desk.py",
     "            if open_notional + notional > ceiling:",
     "            if False:",
     ["test_headroom_under_the_leverage_rule"]),
    ("A9", "agents/desk.py",
     "        if self.orders_left <= 0:\n            raise Refused(\"no orders left in this session\")",
     "        if False:\n            raise Refused(\"no orders left in this session\")",
     ["test_orders_per_session"]),
    ("A10", "agents/desk.py",
     "        if coin not in self.perps:",
     "        if False:",
     ["test_only_perps_on_the_accounts_list"]),
    ("A11", "agents/ai_trader.py",
     "            if spent >= budget_usd:",
     "            if False:",
     ["test_budget_stops_before_the_turns_tools_run"]),
    ("A12", "agents/desk.py",
     "        if not self.send:\n            return {\"status\": \"not_sent\", \"order\": order}",
     "        if False:\n            return {\"status\": \"not_sent\", \"order\": order}",
     ["test_no_orders_mode_sends_nothing"]),
    ("A13", "agents/desk.py",
     "        if offer[\"total_to_pay_usdc\"] > self.max_price:",
     "        if False:",
     ["test_buy_needs_the_listing_price_and_the_cap"]),
    ("A14", "agents/desk.py",
     "        if self.purchases_left <= 0:",
     "        if False:",
     ["test_one_purchase_approving_the_exact_price"]),
    ("A15", "agents/ai_trader.py",
     "    if fallbacks and model in FALLBACK_MODELS:",
     "    if False:",
     ["test_opus_asks_for_adaptive_thinking_and_default_fallbacks"]),
    ("A16", "agents/desk.py",
     "        if notional < MIN_ORDER_USDC:",
     "        if False:",
     ["test_minimum_and_per_order_cap"]),
    ("A17", "agents/ai_trader.py",
     "        if message.stop_reason == \"refusal\":",
     "        if False:",
     ["test_refusal_and_truncation_run_no_tools"]),
    ("A18", "agents/desk.py",
     "            if c.core_spot_balance(pool, 0)[\"total\"] < view(pool, \"capitalNeeded()\", \"uint64\"):",
     "            if False:",
     ["test_listing_shows_only_pools_that_can_sell_now"]),
    ("A19", "agents/desk.py",
     "        if self.graduations_left <= 0:",
     "        if False:",
     ["test_graduation_once_with_a_readable_refusal"]),
    ("A20", "agents/desk.py",
     '        if offer["total_to_pay_usdc"] > self.max_price:',
     '        if offer["price_usdc"] > self.max_price:',
     ["test_the_platform_fee_counts_toward_the_cap_and_the_approval"]),
    ("A21", "agents/desk.py",
     '        total = offer["_price_units"] + self.fee_units',
     '        total = offer["_price_units"]',
     ["test_the_platform_fee_counts_toward_the_cap_and_the_approval"]),
    ("A30", "agents/desk.py",
     '            if side != "buy":',
     "            if False:",
     ["test_a_sell_under_the_market_counts_at_the_mid", "test_headroom_counts_a_sell_at_the_mid"]),
    ("A31", "agents/desk.py",
     "                notional = max(float(px), market_mid(coin)) * float(sz)",
     "                notional = market_mid(coin) * float(sz)",
     ["test_a_sell_under_the_market_counts_at_the_mid"]),
    ("A32", "agents/desk.py",
     "    if not math.isfinite(mid) or mid <= 0:",
     "    if False:",
     ["test_a_sell_without_a_usable_mid_is_refused"]),
    ("A33", "agents/desk.py",
     '                "trader_share_of_challenge_profit_pct": ch_share_bps / 100,\n'
     '                "trader_share_of_funded_profit_pct": funded_share_bps / 100,\n'
     '                "funded_capital_after_passing_usdc": usd(funded),',
     '                "trader_share_of_challenge_profit_pct": funded_share_bps / 100,\n'
     '                "trader_share_of_funded_profit_pct": ch_share_bps / 100,\n'
     '                "funded_capital_after_passing_usdc": usd(funded),',
     ["test_listing_shows_only_pools_that_can_sell_now"]),
    ("A34", "agents/desk.py",
     '                "trader_share_of_challenge_profit_pct": ch_share_bps / 100,\n'
     '                "trader_share_of_funded_profit_pct": funded_share_bps / 100,\n'
     '                "passes_when":',
     '                "trader_share_of_challenge_profit_pct": funded_share_bps / 100,\n'
     '                "trader_share_of_funded_profit_pct": ch_share_bps / 100,\n'
     '                "passes_when":',
     ["test_account_view_keeps_the_two_shares_apart"]),
    # ── keeper (Python unittest) ──
    ("K1", "ops/keeper.py",
     'if entry["address"].lower() != factory.lower() or entry["topics"][0] != CHALLENGE_CREATED:',
     'if entry["topics"][0] != CHALLENGE_CREATED:',
     ["test_an_rpc_that_ignores_the_address_filter_changes_nothing"]),
    ("K2", "ops/keeper.py",
     '"address": factory, "topics": [CHALLENGE_CREATED],',
     '"topics": [CHALLENGE_CREATED],',
     ["test_follows_pools_named_by_the_factorys_challenge_events_only"]),
    ("K3", "ops/keeper.py",
     'entry["topics"][2][-40:]',
     'entry["topics"][1][-40:]',
     ["test_follows_pools_named_by_the_factorys_challenge_events_only"]),
    ("K4", "ops/keeper.py",
     "return not (stage == IDLE and challenge == ZERO)",
     "return True",
     ["test_idle_pool_is_dropped_and_comes_back_with_its_next_challenge"]),
    ("K5", "ops/keeper.py",
     '            stop(wallet, ch, "breach", cancels, extra, dry)',
     "            pass",
     ["test_breach_names_open_orders_and_positions_outside_the_rules"]),
    ("K6", "ops/keeper.py",
     "STOPPED = (BREACHED, EXPIRED, FORFEITED, PASSED, ABORTED)",
     "STOPPED = (BREACHED, EXPIRED, FORFEITED, PASSED)",
     ["test_stopped_states_match_is_stopped", "test_aborted_is_one_of_the_stopped_states"]),
    ("K7", "ops/keeper.py",
     "hi = min(self.next_block + self.window - 1, end)",
     "hi = end",
     ["test_logs_are_read_in_windows_and_the_state_resumes"]),
    ("K8", "ops/keeper.py",
     "return now % 86400 < CHECKPOINT_WINDOW",
     "return True",
     ["test_checkpoint_only_just_after_midnight_and_once_a_day"]),
    ("K9", "ops/keeper.py",
     "CREATED, ACTIVE, BREACHED, EXPIRED, FORFEITED, PASSED, ABORTED, SETTLED = range(1, 9)",
     "CREATED, ACTIVE, BREACHED, EXPIRED, FORFEITED, PASSED, ABORTED, SETTLED = range(0, 8)",
     ["test_status_and_stage_numbers"]),
    # Not "= hi": that leaves the cursor inside the window it just read, the loop asks for the
    # same window forever and the run times out instead of the test failing. A mutation has to
    # end, and this one is the defect that matters anyway -- a block skipped every window.
    ("K10", "ops/keeper.py",
     "            self.next_block = hi + 1",
     "            self.next_block = hi + 2",
     ["test_logs_are_read_in_windows_and_the_state_resumes"]),
    ("K11", "ops/keeper.py",
     'elif now > view(ch, "createdAt()", "uint64") + START_WINDOW:',
     "elif True:",
     ["test_aborts_only_after_the_start_window"]),
    ("K12", "ops/keeper.py",
     'if to_checksum_address(state["factory"]) != self.factory:',
     "if False:",
     ["test_state_of_another_factory_is_refused"]),
    ("K13", "ops/keeper.py",
     "names[p[\"position\"][\"coin\"]] not in allowed",
     "names[p[\"position\"][\"coin\"]] in allowed",
     ["test_breach_names_open_orders_and_positions_outside_the_rules"]),
    ("K14", "ops/keeper.py",
     '    if dry:\n        log("would_send"',
     '    if False:\n        log("would_send"',
     ["test_dry_run_sends_nothing"]),
    ("K15", "ops/keeper.py",
     "except Exception as exc:  # one failed call must not stop the pass",
     "except ZeroDivisionError as exc:",
     ["test_one_failed_call_does_not_stop_the_pass"]),
    ("K18", "ops/keeper.py",
     "        if not 1 <= window <= MAX_LOG_WINDOW:",
     "        if False:",
     ["test_log_windows_stay_within_what_hyperevm_accepts"]),
    ("K19", "ops/keeper.py",
     "MAX_LOG_WINDOW = 50  # blocks per eth_getLogs call that HyperEVM accepts",
     "MAX_LOG_WINDOW = 1000  # blocks per eth_getLogs call that HyperEVM accepts",
     ["test_log_windows_stay_within_what_hyperevm_accepts"]),
    ("K20", "ops/keeper.py",
     "        except Exception as exc:  # the RPC or the info API failed; the next pass retries",
     "        except ZeroDivisionError as exc:",
     ["test_the_service_logs_a_failed_pass_instead_of_dying"]),
    ("K36", "ops/keeper.py",
     '    if role.get("role") == "agent" and agent_of == account.lower():',
     "    if True:",
     ["test_a_cut_that_landed_is_left_alone"]),
    ("K37", "ops/keeper.py",
     'if key == ZERO or latest < view(account, "cutBlock()", "uint64") + RECUT_AFTER_BLOCKS:',
     "if key == ZERO:",
     ["test_a_cut_key_that_still_trades_is_cut_again"]),
    ("K38", "ops/keeper.py",
     "        recut_if_uncut(wallet, ch, latest, dry)",
     "        pass",
     ["test_a_cut_key_that_still_trades_is_cut_again"]),
    ("K39", "ops/keeper.py",
     "            recut_if_uncut(wallet, pool, latest, dry)",
     "            pass",
     ["test_a_closing_pool_whose_cut_key_still_trades_is_cut_again"]),
    ("K40", "ops/keeper.py",
     ' and agent_of == account.lower():',
     ":",
     ["test_a_cut_that_landed_is_left_alone"]),
    ("K41", "ops/deploy_testnet.py",
     "CHALLENGE_FEE = 700_000",
     "CHALLENGE_FEE = 0",
     ["test_every_contract_is_on_disk_before_the_next_is_sent"]),
    ("K42", "ops/deploy_testnet.py",
     '        ("setChallengeFee", factory, "setChallengeFee(uint256,address)", ["uint256", "address"],\n         [CHALLENGE_FEE, deployer.address]),\n',
     "",
     ["test_every_contract_is_on_disk_before_the_next_is_sent", "test_a_late_failure_leaves_the_addresses_on_disk"]),
    ("K43", "ops/keeper.py",
     '        if view(ch, "keySpoiled()", "bool"):',
     "        if False:",
     ["test_a_spoiled_key_is_aborted_at_once"]),
    ("K44", "ops/make_demo_keys.py",
     "os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)",
     "os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)",
     ["test_keys_are_owner_only_and_only_addresses_are_printed", "test_one_owner_only_key_the_spike_tools_read"]),
    ("K45", "ops/make_demo_keys.py",
     "    os.chmod(out, 0o700)  # mkdir's mode is cut by the umask\n",
     "",
     ["test_keys_are_owner_only_and_only_addresses_are_printed"]),
    ("K46", "ops/make_demo_keys.py",
     "    if out.exists():",
     "    if False:",
     ["test_keys_never_go_into_a_directory_that_exists"]),
    ("K47", "ops/make_demo_keys.py",
     "    if directory.stat().st_mode & 0o077:",
     "    if False:",
     ["test_an_open_directory_or_an_odd_name_is_refused"]),
    ("K48", "ops/make_demo_keys.py",
     "os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)",
     "os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)",
     ["test_a_wallet_key_is_never_replaced"]),
    ("K49", "ops/make_demo_keys.py",
     '    if not re.fullmatch(r"[a-z][a-z0-9-]{0,31}", name):',
     "    if False:",
     ["test_an_open_directory_or_an_odd_name_is_refused"]),
    ("K50", "ops/make_demo_keys.py",
     "    if not directory.is_dir():",
     "    if False:",
     ["test_the_directory_must_exist_and_be_one"]),
    ("K16", "ops/deploy_testnet.py",
     "    if proc.returncode != 0:",
     "    if False:",
     ["test_git_failing_stops_the_deployment"]),
    ("K17", "ops/deploy_testnet.py",
     '    if not re.fullmatch(r"[0-9a-f]{40}", commit):',
     "    if False:",
     ["test_no_commit_or_uncommitted_inputs_stop_it"]),
    ("K21", "ops/deploy_testnet.py",
     "        if key in keys:",
     "        if False:",
     ["test_the_registry_rules_are_checked_before_anything_is_deployed"]),
    ("K22", "ops/deploy_testnet.py",
     "    record[\"status\"] = \"incomplete\"",
     "    return",
     ["test_a_late_failure_leaves_the_addresses_on_disk",
      "test_a_failed_deployment_keeps_the_earlier_ones_and_goes_back_to_small_blocks",
      "test_failing_to_leave_big_blocks_marks_the_record"]),
    ("K23", "ops/deployments.py",
     "    if record.get(\"status\") != \"complete\":",
     "    if False:",
     ["test_a_late_failure_leaves_the_addresses_on_disk"]),
    ("K24", "spike/hlspike/common.py",
     'RPC_URL = os.environ.get("COLOSSEUM_RPC_URL", "https://rpc.hyperliquid-testnet.xyz/evm")',
     'RPC_URL = "https://rpc.hyperliquid-testnet.xyz/evm"',
     ["test_a_dedicated_rpc_replaces_the_public_one"]),
    ("K25", "ops/deploy_testnet.py",
     "    save(path, record)\n    return addr, rcpt",
     "    return addr, rcpt",
     ["test_every_contract_is_on_disk_before_the_next_is_sent"]),
    ("K26", "ops/deploy_testnet.py",
     "            big_blocks(deployer, False)\n    except BaseException as exc:",
     "            big_blocks(deployer, False)\n    except ZeroDivisionError as exc:",
     ["test_a_failed_deployment_keeps_the_earlier_ones_and_goes_back_to_small_blocks",
      "test_failing_to_leave_big_blocks_marks_the_record"]),
    ("K27", "ops/deploy_testnet.py",
     "        finally:\n            big_blocks(deployer, False)",
     "        except ZeroDivisionError:\n            big_blocks(deployer, False)",
     ["test_every_contract_is_on_disk_before_the_next_is_sent",
      "test_a_failed_deployment_keeps_the_earlier_ones_and_goes_back_to_small_blocks"]),
    ("K28", "ops/deploy_testnet.py",
     "    tmp = path.with_name(path.name + \".tmp\")",
     "    tmp = path  # written in place",
     ["test_a_write_that_fails_leaves_the_previous_record"]),
    ("K29", "ops/deploy_testnet.py",
     "        tmp.unlink(missing_ok=True)",
     "        pass",
     ["test_a_write_that_fails_leaves_the_previous_record"]),
    ("K30", "ops/keeper.py",
     "        if max_windows < 1:",
     "        if False:",
     ["test_a_pass_always_reads_logs"]),
    ("K31", "spike/hlspike/common.py",
     '            if not (isinstance(error, dict) and error.get("code") == RATE_LIMITED):',
     "            if True:",
     ["test_a_throttled_call_is_retried", "test_it_gives_up_in_the_end"]),
    ("K32", "spike/hlspike/common.py",
     "        if resp.status_code != 429:",
     "        if True:",
     ["test_a_throttled_call_is_retried"]),
    ("K33", "spike/hlspike/common.py",
     '        if "already known" not in str(exc):',
     "        if True:",
     ["test_already_known_waits_for_the_receipt"]),
    ("K34", "ops/deploy_testnet.py",
     "            os.fsync(fh.fileno())",
     "            pass",
     ["test_the_new_record_is_on_disk_before_it_replaces_the_old_one"]),
    ("K35", "ops/deploy_testnet.py",
     "            os.fsync(directory)",
     "            pass",
     ["test_the_new_record_is_on_disk_before_it_replaces_the_old_one"]),
    # ── app (node --test) ──
    ("J8", "app/lib/nav.js",
     "    const page = mount();",
     "    const page = (globalThis.sharedPage ??= mount());",
     ["a page that finishes loading after the user moved on stays off screen"]),
    ("J9", "app/lib/nav.js",
     "      if (id === current) onError(page, err);",
     "      onError(page, err);",
     ["only the page on screen reports its failure"]),
    ("J10", "app/lib/nav.js",
     '  return !passed && hash !== "#/terms";',
     "  return false;",
     ["every page but the terms asks the entry question until it is answered"]),
    ("J11", "app/lib/ui.js",
     "    if (box) box.textContent = `Could not load: ${friendly(err)}`;",
     "    return err;",
     ["a panel that fails to load says so"]),
    ("J20", "app/lib/keys.js",
     "  for (const address of [current, boundNow, cutKey]) {",
     "  for (const address of [current, boundNow]) {",
     ["the key panel draws from contract state, in a handful of reads"]),
    ("J21", "app/lib/keys.js",
     "  return !address || String(address).toLowerCase() === ZERO;",
     "  return !address;",
     ["an account that never held a key reads nothing about keys"]),
    ("J22", "app/lib/keys.js",
     "  return Boolean(a && b && String(a).toLowerCase() === String(b).toLowerCase());",
     "  return Boolean(a && b && String(a) === String(b));",
     ["the same address bound and approved is named once"]),
    ("J23", "app/lib/ui.js",
     "    if (Number(e.code) === -32005) return RPC;",
     "    if (false) return RPC;",
     ["a rate-limited RPC is said in words, not pasted as a payload"]),
    ("J24", "app/views/verify.js",
     "  const reg = chain.registry();",
     "  const reg = chain.registry();\n  await account.queryFilter(account.filters.AgentCut(), 0, 99);",
     ["the panel may not read the event log while it loads"]),
    ("J29", "app/lib/keys.js",
     "    role: await Promise.resolve().then(() => reads.role(address)).catch(() => null),",
     "    role: await reads.role(address),",
     ["Hyperliquid failing does not take the contract's own answer down with it"]),
    ("J30", "app/lib/keys.js",
     "    chainReads: 4 + named.length,",
     "    chainReads: 4,",
     ["the key panel draws from contract state, in a handful of reads"]),
    ("J36", "app/lib/batch.js",
     "    out.push(...(await Promise.all(items.slice(i, i + size).map((item, j) => make(item, i + j)))));",
     "    out.push(...(await Promise.all(items.map((item, j) => make(item, j)))));",
     ["a fan-out read never hands the node a batch it refuses"]),
    ("J37", "app/lib/batch.js",
     "export const MAX_BATCH = 20;",
     "export const MAX_BATCH = 64;",
     ["a fan-out read never hands the node a batch it refuses"]),
    ("J38", "app/views/economics.js",
     "  if (!(pool >= MIN_POOL)) {",
     "  if (false) {",
     ["the default mode is the decision's pool, and nothing below the minimum is one"]),
    ("J39", "app/views/economics.js",
     "    if (!m) throw new Error(`\"${part.trim()}\" is not a seat: write it as size\u00d7count, for example 50000x1`);",
     "    if (!m) return { F: 0, count: 0 };",
     ["seats are read as size x count, and a line that is not one is refused"]),
    ("J40", "app/lib/floor.js",
     "  if (!Object.prototype.hasOwnProperty.call(tables.cells, cellKey(scenario, mode, dd, daily, target))) {\n    return { offGrid: true };\n  }",
     "  if (false) {\n    return { offGrid: true };\n  }",
     ["the price floor is the floor of the investor's own rules, or nothing"]),
    ("J41", "app/lib/floor.js",
     "  return Math.abs(ratio - CHALLENGE_RATIO) > tolerance ? ratio : null;",
     "  return null;",
     ["a challenge account away from a tenth of the seat is called out"]),
    ("J42", "app/views/economics.js",
     "    asset_list: values.assetList || \"default\",",
     "    asset_list: \"wide\",",
     ["the asset list reaches the calculator, and the page cannot show a tail without naming it"]),
    ("J43", "app/views/economics.js",
     "    ${row(\"Measured on\", `${esc(c.day)}, a pool whose rules allow <strong>${esc(c.coins.join(\", \"))}</strong>`)}",
     "    ${row(\"Measured on\", `${esc(c.day)}`)}",
     ["the Economics page shows the coins and the caption, not just a percentage"]),
    ("J44", "app/views/economics.js",
     "    <p class=\"notice\"><strong>${esc(c.note)}</strong></p>",
     "",
     ["the Economics page shows the coins and the caption, not just a percentage"]),
    ("J31", "app/lib/floor.js",
     "  if (ratio !== null) return { offRatio: ratio };",
     "",
     ["no floor for a pool the model does not describe, rather than the floor of another pool"]),
    ("J32", "app/views/economics.js",
     "  return withinSeatCap(seats);",
     "  return seats;",
     ["a seat count cannot freeze the page"]),
    ("J33", "app/views/economics.js",
     "  if (!Number.isFinite(reserve) || reserve < 0) {",
     "  if (!Number.isFinite(reserve)) {",
     ["the reserve is zero or more dollars, never a division by zero"]),
    ("J34", "app/views/economics.js",
     "    clearCascade(\"Fix the pool above to see what a cascade does to it.\");\n    return;",
     "    return;",
     ["the page names what the model covers and what it does not"]),
    ("J35", "app/views/economics.js",
     "<strong>Every number the calculator returns is a model, not a measurement.</strong>",
     "<strong>Every number on this page is a model, not a measurement.</strong>",
     ["the page names what the model covers and what it does not"]),
    ("J45", "app/views/economics.js",
     "  const layout = defaultLayout(pool);\n  withinSeatCap(layout.seats);",
     "  const layout = defaultLayout(pool);",
     ["a pool size cannot freeze the page either"]),
    ("J46", "app/lib/demo.js",
     "  capital: 70,",
     "  capital: 90,",
     ["the new-pool form starts with the demo pool, one the model prices, above what a challenge costs it"]),
    ("J47", "app/lib/demo.js",
     "  price: 7,",
     "  price: 3,",
     ["the new-pool form starts with the demo pool, one the model prices, above what a challenge costs it"]),
    ("J48", "app/views/pools.js",
     'value="${D.funded}"',
     'value="10000"',
     ["the new-pool form starts with the demo pool, one the model prices, above what a challenge costs it"]),
    ("J49", "app/lib/ui.js",
     '  if (all.some((e) => e.code === "BAD_DATA")) {',
     "  if (false) {",
     ["a page that fails to load names a cause only when the error shows one"]),
    ("J50", "app/lib/ui.js",
     "  if (all.some(unreachable)) {",
     "  if (false) {",
     ["a page that fails to load names a cause only when the error shows one"]),
    ("J51", "app/lib/ui.js",
     "    if (Number(e.info?.responseStatus) === 429) return RPC;",
     "",
     ["a page that fails to load names a cause only when the error shows one"]),
    ("J53", "app/app.js",
     '    ${hint ? `<p class="muted">${esc(hint)}</p>` : ""}</section>`);',
     '    <p class="muted">The public testnet RPC is rate limited; wait a moment and reload.</p></section>`);',
     ["a page that fails to load names a cause only when the error shows one"]),
    ("J54", "app/lib/ui.js",
     "  if (Number.isFinite(status)) return status >= 500 || status === 408 || status === 425;",
     "  if (Number.isFinite(status)) return status >= 400;",
     ["a page that fails to load names a cause only when the error shows one"]),
    ("J55", "app/lib/ui.js",
     "    if (Number(e.status) === 429) return HYPERLIQUID;",
     "",
     ["a page that fails to load names a cause only when the error shows one"]),
    ("J57", "app/lib/ui.js",
     "    if (Number(e.status) === 429) return HYPERLIQUID;",
     "    if (Number(e.status) === 429) return RPC;",
     ["a page that fails to load names a cause only when the error shows one"]),
    ("J56", "app/lib/hl.js",
     ", { status: res.status });",
     ");",
     ["a page that fails to load names a cause only when the error shows one"]),
    ("K51", "ops/keeper.py",
     '                log("scan_stopped", at_block=self.next_block, error=str(exc)[:200])\n                break\n',
     "                raise\n",
     ["test_a_refused_read_keeps_the_blocks_and_the_rest_of_the_pass"]),
    ("K52", "ops/keeper.py",
     "            # On disk window by window. A refused read is handled above, but a process killed\n"
     "            # mid-scan -- a redeploy restarts this service -- would otherwise start the next run\n"
     "            # at the block this pass began at, which is the rescan the loop exists to avoid. It\n"
     "            # also keeps what was read from the venue reads below, which can be refused too.\n"
     "            self.save()\n",
     "",
     # A pass that finishes saves at its end anyway; what this line alone keeps is the scan of a
     # pass that is killed part way, which is what a redeploy does to this service.
     ["test_an_interrupted_scan_keeps_the_windows_that_finished"]),
    ("J58", "app/lib/wallet.js",
     "    if (cancelled(err)) throw err;\n  }\n  if ((await chainOf(eth)) === want) return \"switched\";",
     "    throw err;\n  }\n  if ((await chainOf(eth)) === want) return \"switched\";",
     ["the wallet is put on this chain by what it is on, not by how it refuses"]),
    ("J59", "app/lib/wallet.js",
     '  if ((await chainOf(eth)) === want) return "added";',
     '  return "added";',
     ["the wallet is put on this chain by what it is on, not by how it refuses"]),
    ("J60", "app/lib/hlsend.js",
     '  if (/unified account/i.test(String(why || ""))) {',
     "  if (false) {",
     ["spot transfer: a refusal that has a way out says what it is",
      "spot transfer: the refusal the button throws carries the way out"]),
    ("J63", "app/lib/hlsend.js",
     '    const advice = whatToDo(why, { destination, amount: canonical(amount) });\n'
     '    throw new Error(`Hyperliquid refused the transfer: ${why}${advice ? `. ${advice}` : ""}`);',
     "    throw new Error(`Hyperliquid refused the transfer: ${why}`);",
     ["spot transfer: the refusal the button throws carries the way out"]),
    ("J64", "app/lib/wallet.js",
     "    if (cancelled(err)) throw err;\n"
     "    // The wallet refused to take the chain at all. Its own words are no use to the visitor, so\n"
     "    // they get the four fields instead: this is the one path where the network is still missing.\n"
     "    throw new Error(`This wallet would not add ${config.chainName}. Add it by hand: network name `\n"
     "      + `${config.chainName}, RPC URL ${config.rpc}, chain id ${config.chainId}, currency symbol `\n"
     "      + `${config.nativeCurrency.symbol}.`);",
     "    throw err;",
     ["the wallet is put on this chain by what it is on, not by how it refuses"]),
    ("J61", "app/views/economics.js",
     "    low: Math.min(...shares(\"default\")),",
     "    low: 0.24,",
     ["who takes the loss reads the day's figures from the table, and the page says them once"]),
    ("J62", "app/views/economics.js",
     "    wideLiquidated: Math.max(mix.seats_liquidated.open, mix.seats_liquidated.worst),",
     "    wideLiquidated: 3,",
     ["who takes the loss reads the day's figures from the table, and the page says them once"]),
    ("J65", "app/lib/verdict.js",
     '  if (Number(recorded)) return { kind: "recorded", reason: Number(recorded) };',
     '  if (false) return { kind: "recorded", reason: Number(recorded) };',
     ["a stop shows the reason the contract recorded, not one computed on an empty account"]),
    ("J67", "app/lib/verdict.js",
     '  if (finished) return { kind: "finished-with-no-rule-broken" };',
     "",
     ["a stop shows the reason the contract recorded, not one computed on an empty account"]),
    ("J66", "app/lib/verdict.js",
     '  return verdict.kind !== "live";',
     "  return false;",
     ["a stop shows the reason the contract recorded, not one computed on an empty account"]),
    # ── the identity gate and its list of known commits (bash) ──
    ("S1", "scripts/identity-check.sh",
     '  if [ -n "$entry" ]; then',
     "  if true; then",
     ["personal author", "personal committer"]),
    ("S2", "scripts/identity-check.sh",
     'grep "^${sha} "',
     'grep "${sha:0:8}"',
     ["a short id does not match"]),
    ("J15", "app/lib/hlsend.js",
     "  if (v < 27) v += 27;",
     "",
     ["spot transfer: a 65-byte signature becomes r, s and v"]),
    ("J16", "app/lib/hlsend.js",
     'const message = { hyperliquidChain: "Testnet",',
     'const message = { hyperliquidChain: "Mainnet",',
     ["spot transfer: the data the wallet signs is Hyperliquid's"]),
    ("J17", "app/lib/hlsend.js",
     " || destination.toLowerCase() === ZERO) {",
     ") {",
     ["spot transfer: amounts are canonical, and a bad field is refused before signing"]),
    ("J18", "app/lib/hlsend.js",
     "token, amount: canonical(amount), time };",
     "token, amount, time };",
     ["spot transfer: amounts are canonical, and a bad field is refused before signing"]),
    ("J19", "app/lib/hlsend.js",
     '  if (answer && answer.status === "ok") return null;',
     "  if (answer) return null;",
     ["spot transfer: only an ok answer counts as sent"]),
    ("J14", "app/lib/gateway.js",
     '  url.search = "";',
     "",
     ["the gateway is reached over https unless it runs on this machine"]),
    ("J7", "app/lib/gateway.js",
     'if (url.protocol !== "https:" && !(url.protocol === "http:" && local)) {',
     "if (false) {",
     ["the gateway is reached over https unless it runs on this machine"]),
    # The shared pool's page (app/lib/shared.js). "PJ": the second window's prefix, run by node.
    ("PJ1", "app/lib/shared.js",
     "  if (deposit < min) throw new Error(",
     "  if (false) throw new Error(",
     ["a deposit below the pool's minimum is refused before the wallet is asked"]),
    ("PJ2", "app/lib/shared.js",
     "return { deposit, cost: deposit + NEW_ACCOUNT_FEE };",
     "return { deposit, cost: deposit };",
     ["a deposit below the pool's minimum is refused before the wallet is asked"]),
    ("PJ3", "app/lib/shared.js",
     "    .filter((t) => BigInt(t.spot) >= min)",
     "    .filter((t) => BigInt(t.spot) > 0n)",
     ["a point names only tickets holding a deposit it can take, in the order given, eight at most"]),
    ("PJ4", "app/lib/shared.js",
     "    .slice(0, MAX_PER_POINT)\n",
     "",
     ["a point names only tickets holding a deposit it can take, in the order given, eight at most"]),
    ("PJ5", "app/lib/shared.js",
     "const total = e * 100n + c;",
     "const total = e + c;",
     ["a payment's two parts are said apart, and the total with them"]),
    ("PJ6", "app/lib/shared.js",
     "if (!/^\\d+(\\.\\d{1,8})?$/.test(t))",
     "if (!/^\\d+(\\.\\d+)?$/.test(t))",
     ["Hyperliquid's balance strings become spot units exactly, or not at all"]),
    ("PJ7", "app/lib/shared.js",
     "return amount((BigInt(value) * 1_000_000n) / t, 6, 6);",
     "return amount(BigInt(value) / t, 6, 6);",
     ["a share's price and what shares are worth, at the run's numbers"]),
    ("PJ8", "app/lib/shared.js",
     "return BLOCKER[n] || `Unknown reason ${n}.`;",
     "return BLOCKER[n] || BLOCKER[0];",
     ["every reason blocker() can give has its own words"]),
    ("PJ9", "app/lib/shared.js",
     "new Date(Number(args[0]) * 1000)",
     "new Date(Number(args[0]))",
     ["the pool's reverts are said in words; anything else is left to the page"]),
    ("PJ10", "app/lib/shared.js",
     '.padStart(decimals, "0").replace(/0+$/, "");',
     '.padStart(decimals, "0");',
     ["an input gets the number back without separators or padding"]),
    ("PJ11", "app/lib/shared.js",
     'return amount(value, decimals, 6).replace(/(\\.\\d\\d\\d*?)0+$/, "$1");',
     "return amount(value, decimals, 2);",
     ["USDC is shown to the millionth a payment carries, down to cents",
      "a payment's two parts are said apart, and the total with them"]),
    # The page's ABI test reads the contract's source: two fields of the same width swapped there, or
    # two reasons, would decode into the wrong words without any error.
    ("PJ12", "src/shared/SharedPool.sol",
     "        uint96 evm;\n        uint96 core;\n",
     "        uint96 core;\n        uint96 evm;\n",
     ["payments() decodes in the contract's order: when, HyperEVM, HyperCore"]),
    ("PJ13", "src/shared/SharedPool.sol",
     "        PositionsOpen,\n        PayoutInFlight,\n",
     "        PayoutInFlight,\n        PositionsOpen,\n",
     ["the blocker's words follow the contract's reasons, one for one"]),
]

RUNNERS = {
    "M": (["forge", "test"], r"^\[FAIL.*\]\s+(\w+)\("),
    # The shared pool: its own test file is enough, and much faster than the whole suite.
    "P": (["forge", "test", "--match-path", "test/shared/*"], r"^\[FAIL.*\]\s+(\w+)\("),
    # The gate that keeps personal addresses out of this public history, and the list of commits
    # it accepts anyway: its own cases name themselves in the FAIL line.
    "S": (["bash", "scripts/test-identity-check.sh"], r"^FAIL (.+?)(?::|$)"),
    "G": (["spike/.venv/bin/python", "-m", "unittest", "discover", "-s", "gateway/tests", "-t", "."],
          r"^(?:FAIL|ERROR): (\w+) \("),
    "A": (["spike/.venv/bin/python", "-m", "unittest", "discover", "-s", "agents/tests", "-t", "."],
          r"^(?:FAIL|ERROR): (\w+) \("),
    "K": (["spike/.venv/bin/python", "-m", "unittest", "discover", "-s", "ops/tests", "-t", "."],
          r"^(?:FAIL|ERROR): (\w+) \("),
    "J": (["node", "--test", "--test-reporter=tap", *sorted(str(p.relative_to(ROOT)) for p in (ROOT / "app" / "tests").glob("*.test.mjs"))],
          r"^\s*not ok \d+ - (.+?)\s*$"),
    # The shared pool's page: its own test file, the way "P" runs only the shared pool's contract tests.
    "PJ": (["node", "--test", "--test-reporter=tap", "app/tests/shared.test.mjs"], r"^\s*not ok \d+ - (.+?)\s*$"),
}


def runner_of(mid: str) -> str:
    """The runner a mutation id names: its two-letter prefix if there is a runner for it, else its first letter."""
    return mid[:2] if mid[:2] in RUNNERS else mid[0]

# A mutation can turn a bounded loop into an endless one; that has to end the run, not hang it.
RUN_TIMEOUT_S = 900


def run_suite(cmd: list[str]) -> subprocess.CompletedProcess:
    """One test run with its own empty bytecode cache. Python trusts a cached .pyc when the
    source's size and modification second match, and a mutation of the same length restored
    within the same second would otherwise keep running as the mutant afterwards."""
    with tempfile.TemporaryDirectory(prefix="mutations-pyc-") as cache:
        env = {**os.environ, "PYTHONPYCACHEPREFIX": cache}
        return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=RUN_TIMEOUT_S, env=env)


def failing_tests(output: str, pattern: str) -> set[str]:
    # Forge: a failure message can contain brackets of its own ("[1.08e8]"), so the pattern
    # takes the last "]" on the line; the test name follows it.
    return set(re.findall(pattern, output, re.M))


def red_tests(cmd: list[str], pattern: str) -> set[str] | None:
    """Names of the red tests, or None if the suite did not run to the end."""
    try:
        proc = run_suite(cmd)
    except subprocess.TimeoutExpired:
        return None
    out = proc.stdout + proc.stderr
    if "Compiler run failed" in out or "Error (" in out or "SyntaxError" in out:
        return None
    return failing_tests(out, pattern)


def baseline(chosen) -> int:
    problems = 0
    for prefix in sorted({runner_of(m[0]) for m in chosen}):
        cmd, pattern = RUNNERS[prefix]
        red = red_tests(cmd, pattern)
        named = {t for m in chosen if runner_of(m[0]) == prefix for t in m[4]}
        if red is None:
            print(f"baseline {prefix}: the suite did not run")
            problems += 1
        elif red & named:
            print(f"baseline {prefix}: already red before any mutation: {sorted(red & named)}")
            problems += 1
    return problems


def check() -> int:
    """Every mutation still points at the code it guards, and no id is used twice.

    A refactor moves a line and the mutation that guarded it stops matching anything. The full
    run says so, but the full run takes minutes and is called by hand, so a mutation can sit
    orphaned for days -- K7 and K10 did, from 23 to 24 Sep 2026, after their own author moved
    the lines they named. This check reads files and nothing else, so CI can afford it on every
    push: a mutation that matches no code, or matches twice, guards nothing either way.
    """
    problems = 0
    seen: dict[str, int] = {}
    for mid, rel, old, _new, _expected in MUTATIONS:
        seen[mid] = seen.get(mid, 0) + 1
        count = (ROOT / rel).read_text().count(old)
        if count != 1:
            print(f"{mid}: {count} matches in {rel}")
            problems += 1
    for mid, times in sorted(seen.items()):
        if times > 1:
            print(f"{mid}: used {times} times")
            problems += 1
    if problems:
        print(f"mutations --check: {problems} mutation(s) guard nothing; fix the text or drop them")
        return 1
    print(f"mutations --check: {len(MUTATIONS)} mutations, each matching once")
    return 0


def run(selected: list[str]) -> int:
    unknown = sorted(set(selected) - {m[0] for m in MUTATIONS})
    if unknown:
        print(f"mutations: no such mutation: {', '.join(unknown)}")
        return 1
    chosen = [m for m in MUTATIONS if not selected or m[0] in selected]
    problems = baseline(chosen)
    if problems:
        print(f"mutations: {problems} problem(s) before mutating; nothing was mutated")
        return 1
    for mid, rel, old, new, expected in sorted(chosen, key=lambda m: (m[0][0] != "M", runner_of(m[0]), int(m[0][len(runner_of(m[0])):]))):
        cmd, pattern = RUNNERS[runner_of(mid)]
        path = ROOT / rel
        original = path.read_bytes()
        text = original.decode()
        count = text.count(old)
        if count != 1:
            print(f"{mid}: NOT APPLIED ({count} matches in {rel})")
            problems += 1
            continue
        path.write_text(text.replace(old, new), encoding="utf-8")
        try:
            try:
                proc = run_suite(cmd)
            except subprocess.TimeoutExpired:
                print(f"{mid}: TIMED OUT after {RUN_TIMEOUT_S}s")
                problems += 1
                continue
            out = proc.stdout + proc.stderr
            if "Compiler run failed" in out or "Error (" in out or "SyntaxError" in out:
                print(f"{mid}: DID NOT COMPILE")
                problems += 1
                continue
            red = failing_tests(out, pattern)
            missing = [t for t in expected if t not in red]
            if missing:
                print(f"{mid}: SURVIVED in {missing} (red: {sorted(red)})")
                problems += 1
            else:
                print(f"{mid}: killed by {expected}" + (f" (also red: {sorted(red - set(expected))})" if red - set(expected) else ""))
        finally:
            path.write_bytes(original)
    if problems:
        print(f"mutations: {problems} problem(s)")
        return 1
    print("mutations: every mutation applied and was caught")
    return 0


if __name__ == "__main__":
    if sys.argv[1:] == ["--check"]:
        sys.exit(check())
    sys.exit(run(sys.argv[1:]))
